<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.DirectoryServices" Version="9.0.9" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.9" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rftim8Atlas\Rftim8Atlas.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="InfiniSwiss\Engineering\DistributedApplications\" />
    <Folder Include="InfiniSwiss\Engineering\WebSecurity\" />
    <Folder Include="InfiniSwiss\TechStack\DotnetQA\" />
    <Folder Include="InfiniSwiss\TechStack\DotnetWebAPIQA\" />
    <Folder Include="InfiniSwiss\TechStack\WPF_XAML_WinUI\" />
  </ItemGroup>

</Project>
