<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CP\LeetCode\IO\_00036_ValidSudoku_Input.txt" />
    <None Remove="CP\LeetCode\IO\_00036_ValidSudoku_Output.txt" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="CP\LeetCode\IO\_00036_ValidSudoku_Input.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="CP\LeetCode\IO\_00036_ValidSudoku_Output.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
