namespace Rftim8LeetCode.Temp
{
    public class _00389_FindTheDifference
    {
        /// <summary>
        /// You are given two strings s and t.
        /// String t is generated by random shuffling string s and then add one more letter at a random position.
        /// Return the letter that was added to t.
        /// </summary>
        public _00389_FindTheDifference()
        {
            Console.WriteLine(FindTheDifference0("abcd", "abcde"));
            Console.WriteLine(FindTheDifference0("", "y"));
        }

        public static char FindTheDifference0(string a0, string a1) => RftFindTheDifference0(a0, a1);

        public static char FindTheDifference1(string a0, string a1) => RftFindTheDifference1(a0, a1);

        private static char RftFindTheDifference0(string s, string t)
        {
            int n = s.Length;
            Dictionary<char, int> x = [];

            for (int i = 0; i < n; i++)
            {
                if (!x.TryGetValue(s[i], out int value)) x.Add(s[i], 1);
                else x[s[i]] = ++value;
            }

            int m = t.Length;
            Dictionary<char, int> y = [];

            for (int i = 0; i < m; i++)
            {
                if (!y.TryGetValue(t[i], out int value)) y.Add(t[i], 1);
                else y[t[i]] = ++value;
            }

            foreach (KeyValuePair<char, int> item in y)
            {
                if (!x.TryGetValue(item.Key, out int value)) return item.Key;
                if (value != item.Value) return item.Key;
            }

            return ' ';
        }

        private static char RftFindTheDifference1(string s, string t)
        {
            int res = 0;
            s += t;

            for (int i = 0; i < s.Length; i++)
            {
                res ^= s[i];
            }

            return (char)res;
        }
    }
}
