<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>295b5456-c168-4de5-a84d-272a46739bfd</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="NewFolder\**" />
	  <EmbeddedResource Remove="NewFolder\**" />
	  <None Remove="NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
		<PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Rftim8Atlas\Rftim8Atlas.csproj" />
		<ProjectReference Include="..\Rftim8Convoy\Rftim8Convoy.csproj" />
	</ItemGroup>

</Project>
