<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Rftim8Convoy\Rftim8Convoy.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="RftResource.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>RftResource.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="RftResource.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>RftResource.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
